import './globals.css'


export const  metadata = {
  title: 'Google',
  description: 'Generated by shaurya'
}
export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
